version: '3.8'
services:
  flashlog:
    build:
      context: ./backend/flashlog_service
    ports:
      - '8001:8001'
    environment:
      - PORT=8001

  entregagov:
    build:
      context: ./backend/entregagov_service
    ports:
      - '8002:8002'
    environment:
      - PORT=8002

  gateway:
    build:
      context: ./backend/gateway
    ports:
      - '8000:8000'
    environment:
      - FLASHLOG_URL=http://flashlog:8001
      - ENTREGAGOV_URL=http://entregagov:8002
    depends_on:
      - flashlog
      - entregagov

  frontend:
    build:
      context: ./frontend
    ports:
      - '8080:80'
    depends_on:
      - gateway
